import type { ExtensionManifest } from '@lingcoo/frame-extension-sdk';

export const frameAdminManifest = {
  routes: [
    {
      id: 'frame.system-info',
      path: '/system/*',
      title: '系统信息',
      description: '查看 Frame 版本、运行面和已安装扩展。',
      permission: 'system.runtime.read',
    },
    {
      id: 'frame.modules',
      path: '/modules/*',
      title: '领域模块',
      description: '所有具体业务都通过明确的领域模块进入系统。',
      permission: 'admin.access',
    },
    {
      id: 'frame.access',
      path: '/access/*',
      title: '身份与访问',
      description: '管理通用账号、会话、角色和资源权限。',
      permission: 'iam.accounts.read',
    },
    {
      id: 'frame.integrations',
      path: '/integrations/*',
      title: '连接',
      description: '管理外部服务连接、加密凭据、连通性和调用记录。',
      permission: 'integrations.read',
    },
    {
      id: 'frame.assets',
      path: '/assets/*',
      title: '媒体资产中心',
      description: '统一管理文件身份、云存储对象、访问方式和领域引用关系。',
      permission: 'assets.read',
    },
    {
      id: 'frame.operations',
      path: '/operations/*',
      title: '任务与事件',
      description: '查看持久化后台任务、重试状态和 Outbox 事件投影。',
      permission: 'jobs.read',
    },
    {
      id: 'frame.observability',
      path: '/observability/*',
      title: '运行状态',
      description: '查看 API、Worker、数据库、请求指标与聚合异常。',
      permission: 'observability.read',
    },
    {
      id: 'frame.notifications',
      path: '/notifications/*',
      title: '通知中心',
      description: '管理站内通知、系统公告和异步邮件投递。',
      permission: 'notifications.read',
    },
    {
      id: 'frame.metadata',
      path: '/metadata/*',
      title: '通用数据基础',
      description: '管理数据字典、分类法、标签和版本化数据交换。',
      permission: 'metadata.read',
    },
    {
      id: 'frame.audit',
      path: '/audit/*',
      title: '审计中心',
      description: '查询关键操作记录、资源上下文和操作者。',
      permission: 'audit.read',
    },
    {
      id: 'frame.presentation',
      path: '/presentation/*',
      title: '品牌与站点呈现',
      description: '统一管理系统标识、品牌色、联系方式和站点呈现。',
      permission: 'presentation.read',
    },
    {
      id: 'frame.account',
      path: '/account/*',
      title: '个人账号与安全',
      description: '维护个人资料、密码和当前账号的登录会话。',
      permission: 'admin.access',
    },
    {
      id: 'frame.settings',
      path: '/settings/*',
      title: '应用设置',
      description: '管理成员权限、连接、品牌、数据基础、审计和应用配置。',
      permission: 'admin.access',
    },
    {
      id: 'frame.help',
      path: '/help/*',
      title: '框架帮助',
      description: '查看框架能力边界、扩展入口和运行流程。',
      permission: 'admin.access',
    },
  ],
  navigation: [
    {
      id: 'frame.settings',
      routeId: 'frame.settings',
      href: '/settings',
      label: '应用设置',
      group: '管理',
      order: 900,
    },
  ],
  searchProviders: [{ id: 'frame.resources', label: '框架资源', permission: 'search.use' }],
} as const satisfies NonNullable<ExtensionManifest['admin']>;
