import type { ExtensionManifest } from '@lingcoo/frame-extension-sdk';

export const frameAdminManifest = {
  routes: [
    {
      id: 'frame.dashboard',
      path: '/',
      title: '基础框架控制台',
      description: '查看运行面、基础服务和框架扩展状态。',
      permission: 'system.runtime.read',
    },
    {
      id: 'frame.modules',
      path: '/modules/*',
      title: '领域模块',
      description: '所有具体业务都通过明确的领域模块进入系统。',
      permission: 'admin.access',
    },
    {
      id: 'frame.access',
      path: '/access/*',
      title: '身份与访问',
      description: '管理通用账号、会话、角色和资源权限。',
      permission: 'iam.accounts.read',
    },
    {
      id: 'frame.integrations',
      path: '/integrations/*',
      title: '外部集成',
      description: '管理服务配置、加密凭据、连通性和调用记录。',
      permission: 'integrations.read',
    },
    {
      id: 'frame.assets',
      path: '/assets/*',
      title: '媒体资产中心',
      description: '统一管理文件身份、云存储对象、访问方式和领域引用关系。',
      permission: 'assets.read',
    },
    {
      id: 'frame.operations',
      path: '/operations/*',
      title: '任务与事件',
      description: '查看持久化后台任务、重试状态和 Outbox 事件投影。',
      permission: 'jobs.read',
    },
    {
      id: 'frame.observability',
      path: '/observability/*',
      title: '运行状态',
      description: '查看 API、Worker、数据库、请求指标与聚合异常。',
      permission: 'observability.read',
    },
    {
      id: 'frame.notifications',
      path: '/notifications/*',
      title: '通知中心',
      description: '管理站内通知、系统公告和异步邮件投递。',
      permission: 'notifications.read',
    },
    {
      id: 'frame.metadata',
      path: '/metadata/*',
      title: '通用数据基础',
      description: '管理数据字典、分类法、标签和版本化数据交换。',
      permission: 'metadata.read',
    },
    {
      id: 'frame.audit',
      path: '/audit/*',
      title: '审计中心',
      description: '查询关键操作记录、资源上下文和操作者。',
      permission: 'audit.read',
    },
    {
      id: 'frame.presentation',
      path: '/presentation/*',
      title: '品牌与站点呈现',
      description: '统一管理系统标识、品牌色、联系方式和站点呈现。',
      permission: 'presentation.read',
    },
    {
      id: 'frame.account',
      path: '/account/*',
      title: '个人账号与安全',
      description: '维护个人资料、密码和当前账号的登录会话。',
      permission: 'admin.access',
    },
    {
      id: 'frame.settings',
      path: '/settings/*',
      title: '框架设置',
      description: '查看并维护已登记的非敏感系统配置。',
      permission: 'system.settings.read',
    },
    {
      id: 'frame.help',
      path: '/help/*',
      title: '框架帮助',
      description: '查看框架能力边界、扩展入口和运行流程。',
      permission: 'admin.access',
    },
  ],
  navigation: [
    {
      id: 'frame.dashboard',
      routeId: 'frame.dashboard',
      href: '/',
      label: '系统概览',
      group: '总览',
      order: 10,
    },
    {
      id: 'frame.modules',
      routeId: 'frame.modules',
      href: '/modules',
      label: '模块扩展',
      group: '架构',
      order: 20,
    },
    {
      id: 'frame.access',
      routeId: 'frame.access',
      href: '/access',
      label: '身份与权限',
      group: '系统',
      order: 30,
    },
    {
      id: 'frame.integrations',
      routeId: 'frame.integrations',
      href: '/integrations',
      label: '外部集成',
      group: '系统',
      order: 40,
    },
    {
      id: 'frame.assets',
      routeId: 'frame.assets',
      href: '/assets',
      label: '媒体资源库',
      group: '资源',
      order: 50,
    },
    {
      id: 'frame.operations',
      routeId: 'frame.operations',
      href: '/operations',
      label: '任务中心',
      group: '运行',
      order: 60,
    },
    {
      id: 'frame.observability',
      routeId: 'frame.observability',
      href: '/observability',
      label: '运行监控',
      group: '运行',
      order: 70,
    },
    {
      id: 'frame.notifications',
      routeId: 'frame.notifications',
      href: '/notifications',
      label: '通知中心',
      group: '运行',
      order: 80,
    },
    {
      id: 'frame.metadata',
      routeId: 'frame.metadata',
      href: '/metadata',
      label: '数据字典与分类',
      group: '数据',
      order: 90,
    },
    {
      id: 'frame.audit',
      routeId: 'frame.audit',
      href: '/audit',
      label: '审计日志',
      group: '系统',
      order: 100,
    },
    {
      id: 'frame.presentation',
      routeId: 'frame.presentation',
      href: '/presentation',
      label: '品牌设置',
      group: '站点',
      order: 110,
    },
    {
      id: 'frame.settings',
      routeId: 'frame.settings',
      href: '/settings',
      label: '系统设置',
      group: '系统',
      order: 130,
    },
    {
      id: 'frame.help',
      routeId: 'frame.help',
      href: '/help',
      label: '框架帮助',
      group: '支持',
      order: 140,
    },
  ],
  searchProviders: [{ id: 'frame.resources', label: '框架资源', permission: 'search.use' }],
} as const satisfies NonNullable<ExtensionManifest['admin']>;
